language: python
python: 3.4
sudo: false

env:
- TOXENV=py26-dj12
- TOXENV=py26-dj13
- TOXENV=py26-dj14
- TOXENV=py26-dj15
- TOXENV=py26-dj16

- TOXENV=py27-dj12
- TOXENV=py27-dj13
- TOXENV=py27-dj14
- TOXENV=py27-dj15
- TOXENV=py27-dj16
- TOXENV=py27-dj17
- TOXENV=py27-dj18
- TOXENV=py27-djmaster

- TOXENV=py32-dj15
- TOXENV=py32-dj16
- TOXENV=py32-dj17
- TOXENV=py32-dj18

- TOXENV=py33-dj15
- TOXENV=py33-dj16
- TOXENV=py33-dj17
- TOXENV=py33-dj18

- TOXENV=py34-dj17
- TOXENV=py34-dj18
- TOXENV=py34-djmaster

- TOXENV=pypy-dj12
- TOXENV=pypy-dj14
- TOXENV=pypy-dj18
- TOXENV=pypy-djmaster

install:
- pip install -U tox

script: tox
