sudo: false
language: python
cache: pip
python:
- 2.7
- 3.4
- 3.5
- 3.6
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: jazzband
  server: https://jazzband.co/projects/django-widget-tweaks/upload
  distributions: sdist bdist_wheel
  password:
    secure: fvFbH0oZGYDad2rik7v0L+G4ItH0g/2v8hoBSajeyt/nEyoEShTh2xBwo5413NGkDaIYtYpP/MVqBy02uMc8oSNgh/rS1tIjiIKE77/YJNuZHyQXnZ+90JA+yGaJc5dOyd4G3szEp2Zzi18ov2KkCt37/arObu8bEbChWaEoJqI=
  on:
    tags: true
    repo: jazzband/django-widget-tweaks
    python: 3.6
